# Generated by Django 4.0.4 on 2022-05-28 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0002_alter_image_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engaged', models.CharField(help_text='Nome do noivo', max_length=250, verbose_name='Noivo')),
                ('fiancee', models.CharField(help_text='Nome da noiva', max_length=250, verbose_name='Noiva')),
                ('icon_center', models.ImageField(upload_to='', verbose_name='Imagem de centro')),
                ('background_image', models.ImageField(upload_to='', verbose_name='Imagem de fundo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
